/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as ContratacoesRouteImport } from './routes/contratacoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as PessoalRouteImport } from './routes/pessoal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratacoesRoute = ContratacoesRouteImport.update({
  id: '/contratacoes',
  path: '/contratacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoalRoute = PessoalRouteImport.update({
  id: '/pessoal',
  path: '/pessoal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparador': typeof ComparadorRoute
  '/contratacoes': typeof ContratacoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pessoal': typeof PessoalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparador': typeof ComparadorRoute
  '/contratacoes': typeof ContratacoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pessoal': typeof PessoalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparador': typeof ComparadorRoute
  '/contratacoes': typeof ContratacoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pessoal': typeof PessoalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comparador' | '/contratacoes' | '/financeiro' | '/pessoal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comparador' | '/contratacoes' | '/financeiro' | '/pessoal'
  id:
    | '__root__'
    | '/'
    | '/comparador'
    | '/contratacoes'
    | '/financeiro'
    | '/pessoal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparadorRoute: typeof ComparadorRoute
  ContratacoesRoute: typeof ContratacoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  PessoalRoute: typeof PessoalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratacoes': {
      id: '/contratacoes'
      path: '/contratacoes'
      fullPath: '/contratacoes'
      preLoaderRoute: typeof ContratacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoal': {
      id: '/pessoal'
      path: '/pessoal'
      fullPath: '/pessoal'
      preLoaderRoute: typeof PessoalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparadorRoute: ComparadorRoute,
  ContratacoesRoute: ContratacoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  PessoalRoute: PessoalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
